### PR TITLE
added zottelf to the list

### PR DESCRIPTION
**Pull request by zottelef**
please add me to the list! Thank you for the great work. All the best! Fabio

### CODE REVIEW

**Comment by isomorphisms** [comment]
Hey @zottelef can you also update the `README.md` in the same place?

**Comment by zottelef** [comment]
@isomorphisms I changed README.md accordingly ... sorry for not noticing that. Hope everything  is ok, now. Thanks

**Comment by isomorphisms** [comment]
Can you also remove the changes to index.html

**Comment by zottelef** [comment]
Removed my entry form index.html. Please check if everything is ok. Fabio

**Comment by isomorphisms** [comment]
thanks Fabio

**Pull request merged**
