### PR TITLE
updated my profile

### PR DESCRIPTION
**Pull request by Emaasit**
Added links to my stackoverflow and r-bloggers profiles

### CODE REVIEW

**Comment by Emaasit** [comment]
@isomorphisms I used the logos. check it out and let me know. Thanks

**Comment by isomorphisms** [comment]
Sorry for the long wait, Daniel. I'll fix this now

**Comment by isomorphisms** [comment]
Daniel, I'm talking about the flair: https://stackoverflow.com/users/flair

**Comment by isomorphisms** [comment]
Can you pull again please? I don't want to have to fix all the merge conflicts.

**Pull request closed without merging**
